/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package de.andycandy.flow

import org.junit.Test

import de.andycandy.flow.App
import spock.lang.Specification

class AppTest extends Specification {
    
	
	@Test
	def "test app evaluate"() {
		setup:
		App app = new App()
		File file = new File(Thread.currentThread().getContextClassLoader().getResource('de/andycandy/flow/flow.dsl').path)
		
		when:
		def result = app.evaluate(file)
		
		then:
		result == [0, 1, 4, 9]
	}
	
}
